spring:
  datasource:
    url: jdbc:postgresql://database-1.cyn4e04ie6r7.us-east-1.rds.amazonaws.com:5432/labdb
    username: postgres
    password:

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
  security:
      oauth2:
        client:
          registration:
            google:
              client-id: 
              client-secret:
              scope:
                - openid
                - profile
                - email